export const FETCH_SIGNED_UP_REQUEST_DETAIL_START = 'FETCH_SIGNED_UP_REQUEST_DETAIL_START';
export const FETCH_SIGNED_UP_REQUEST_DETAIL_FAIL = 'FETCH_SIGNED_UP_REQUEST_DETAIL_FAIL';
export const FETCH_SIGNED_UP_REQUEST_DETAIL_SUCCESS = 'FETCH_SIGNED_UP_REQUEST_DETAIL_SUCCESS';

export const UPDATE_SIGNED_UP_REQUEST_START = 'UPDATE_SIGNED_UP_REQUEST_START';
export const UPDATE_SIGNED_UP_REQUEST_FAIL = 'UPDATE_SIGNED_UP_REQUEST_FAIL';
export const UPDATE_SIGNED_UP_REQUEST_SUCCESS = 'UPDATE_SIGNED_UP_REQUEST_SUCCESS';

export const DELETE_SIGNED_UP_REQUEST_START = 'DELETE_SIGNED_UP_REQUEST_START';
export const DELETE_SIGNED_UP_REQUEST_FAIL = 'DELETE_SIGNED_UP_REQUEST_FAIL';
export const DELETE_SIGNED_UP_REQUEST_SUCCESS = 'DELETE_SIGNED_UP_REQUEST_SUCCESS';