export const FETCH_VOLUNTEER_REQUEST_DETAIL_START = 'FETCH_VOLUNTEER_REQUEST_DETAIL_START';
export const FETCH_VOLUNTEER_REQUEST_DETAIL_FAIL = 'FETCH_VOLUNTEER_REQUEST_DETAIL_FAIL';
export const FETCH_VOLUNTEER_REQUEST_DETAIL_SUCCESS = 'FETCH_VOLUNTEER_REQUEST_DETAIL_SUCCESS';

export const UPDATE_VOLUNTEER_REQUEST_START = 'UPDATE_VOLUNTEER_REQUEST_START';
export const UPDATE_VOLUNTEER_REQUEST_FAIL = 'UPDATE_VOLUNTEER_REQUEST_FAIL';
export const UPDATE_VOLUNTEER_REQUEST_SUCCESS = 'UPDATE_VOLUNTEER_REQUEST_SUCCESS';

export const DELETE_VOLUNTEER_REQUEST_START = 'DELETE_VOLUNTEER_REQUEST_START';
export const DELETE_VOLUNTEER_REQUEST_FAIL = 'DELETE_VOLUNTEER_REQUEST_FAIL';
export const DELETE_VOLUNTEER_REQUEST_SUCCESS = 'DELETE_VOLUNTEER_REQUEST_SUCCESS';