export const FETCH_REQUEST_DETAIL_START = 'FETCH_REQUEST_DETAIL_START';
export const FETCH_REQUEST_DETAIL_FAIL = 'FETCH_REQUEST_DETAIL_FAIL';
export const FETCH_REQUEST_DETAIL_SUCCESS = 'FETCH_REQUEST_DETAIL_SUCCESS';