export const FETCH_REQUEST_DETAIL_START = 'FETCH_REQUEST_DETAIL_START';
export const FETCH_REQUEST_DETAIL_FAIL = 'FETCH_REQUEST_DETAIL_FAIL';
export const FETCH_REQUEST_DETAIL_SUCCESS = 'FETCH_REQUEST_DETAIL_SUCCESS';

export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const DELETE_REQUEST_FAIL = 'DELETE_REQUEST_FAIL';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';