export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const HIDE_AUTH_MODAL = 'HIDE_AUTH_MODAL';
export const SUCCESSFULLY_LOG_IN = 'SUCCESSFULLY_LOG_IN';
export const SUCCESSFULLY_CREATE_ACCOUNT = 'SUCCESSFULLY_CREATE_ACCOUNT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';