export const OPEN_AUTH_MODAL = 'OPEN_AUTH_MODAL';
export const HIDE_AUTH_MODAL = 'HIDE_AUTH_MODAL';
export const SUCCESSFULLY_LOG_IN = 'SUCCESSFULLY_LOG_IN';
export const SUCCESSFULLY_CREATE_ACCOUNT = 'SUCCESSFULLY_CREATE_ACCOUNT';