export const FETCH_REIMBURSEMENT_START = 'FETCH_REIMBURSMENT_START';
export const FETCH_REIMBURSEMENT_FAIL = 'FETCH_REIMBURSMENT_FAIL';
export const FETCH_REIMBURSEMENT_SUCCESS = 'FETCH_REIMBURSMENT_SUCCESS';

export const UPDATE_REIMBURSEMENT_START = 'UPDATE_REIMBURSEMENT_START';
export const UPDATE_REIMBURSEMENT_FAIL = 'UPDATE_REIMBURSEMENT_FAIL';
export const UPDATE_REIMBURSEMENT_SUCCESS = 'UPDATE_REIMBURSEMENT_SUCCESS';

export const DELETE_REIMBURSEMENT_START = 'DELETE_REIMBURSEMENT_START';
export const DELETE_REIMBURSEMENT_FAIL = 'DELETE_REIMBURSEMENT_FAIL';
export const DELETE_REIMBURSEMENT_SUCCESS = 'DELETE_REIMBURSEMENT_SUCCESS';

export const REQUEST_REIMBURSEMENT_START = 'REQUEST_REIMBURSEMENT_START';
export const REQUEST_REIMBURSEMENT_FAIL = 'REQUEST_REIMBURSEMENT_FAIL';
export const REQUEST_REIMBURSEMENT_SUCCESS = 'REQUEST_REIMBURSEMENT_SUCCESS';

