export const FETCH_REQUESTS_START = 'FETCH_REQUESTS_START';
export const FETCH_REQUESTS_FAIL = 'FETCH_REQUESTS_FAIL';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';

export const CREATE_REQUEST_START = 'CREATE_REQUEST_START';
export const CREATE_REQUEST_FAIL = 'CREATE_REQUEST_FAIL';
export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS';