export const FETCH_VOLUNTEER_LIST_START = 'FETCH_VOLUNTEER_LIST_START';
export const FETCH_VOLUNTEER_LIST_FAIL = 'FETCH_VOLUNTEER_LIST_FAIL';
export const FETCH_VOLUNTEER_LIST_SUCCESS = 'FETCH_VOLUNTEER_LIST_SUCCESS';

export const FETCH_VOLUNTEER_DETAIL_START = 'FETCH_VOLUNTEER_DETAIL_START';
export const FETCH_VOLUNTEER_DETAIL_FAIL = 'FETCH_VOLUNTEER_DETAIL_FAIL';
export const FETCH_VOLUNTEER_DETAIL_SUCCESS = 'FETCH_VOLUNTEER_DETAIL_SUCCESS';

export const UPDATE_VOLUNTEER_START = 'UPDATE_VOLUNTEER_START';
export const UPDATE_VOLUNTEER_FAIL = 'UPDATE_VOLUNTEER_FAIL';
export const UPDATE_VOLUNTEER_SUCCESS = 'UPDATE_VOLUNTEER_SUCCESS';

export const DELETE_VOLUNTEER_START = 'DELETE_VOLUNTEER_START';
export const DELETE_VOLUNTEER_FAIL = 'DELETE_VOLUNTEER_FAIL';
export const DELETE_VOLUNTEER_SUCCESS = 'DELETE_VOLUNTEER_SUCCESS';

