export const FETCH_VOLUNTEER_REQUESTS_START = 'FETCH_VOLUNTEER_REQUESTS_START';
export const FETCH_VOLUNTEER_REQUESTS_FAIL = 'FETCH_VOLUNTEER_REQUESTS_FAIL';
export const FETCH_VOLUNTEER_REQUESTS_SUCCESS = 'FETCH_VOLUNTEER_REQUESTS_SUCCESS';

export const REQUEST_SIGNUP_START = 'REQUEST_SIGNUP_START';
export const REQUEST_SIGNUP_FAIL = 'REQUEST_SIGNUP_FAIL';
export const REQUEST_SIGNUP_SUCCESS = 'REQUEST_SIGNUP_SUCCESS';