export const FETCH_DONATION_START = 'FETCH_DONATION_START';
export const FETCH_DONATION_FAIL = 'FETCH_DONATION_FAIL';
export const FETCH_DONATION_SUCCESS = 'FETCH_DONATION_SUCCESS';

export const UPDATE_DONATION_START = 'UPDATE_DONATION_START';
export const UPDATE_DONATION_FAIL = 'UPDATE_DONATION_FAIL';
export const UPDATE_DONATION_SUCCESS = 'UPDATE_DONATION_SUCCESS';

export const DELETE_DONATION_START = 'DELETE_DONATION_START';
export const DELETE_DONATION_FAIL = 'DELETE_DONATION_FAIL';
export const DELETE_DONATION_SUCCESS = 'DELETE_DONATION_SUCCESS';

export const CREATE_DONATION_START = 'CREATE_DONATION_START';
export const CREATE_DONATION_FAIL = 'CREATE_DONATION_FAIL';
export const CREATE_DONATION_SUCCESS = 'CREATE_DONATION_SUCCESS';

